{
# modulesPath,
lib, pkgs, ... }: {
  imports = [
    ./disk-config.nix
    # ./hardware-configuration.nix
  ];
  boot.loader.grub = {
    # no need to set devices, disko will add all devices that have a EF02 partition to the list already
    # devices = [ ];
    efiSupport = true;
    efiInstallAsRemovable = true;
  };

  nix.settings.trusted-users = [ "@wheel" ];
  nixpkgs.config.allowUnfree = true;
  hardware.enableAllFirmware = true;

  services.openssh = {
    enable = true;
    settings = { PasswordAuthentication = false; };
  };

  networking = {
    hostName = "servitro";
    #  useNetworkd=true;
    nameservers = [ "8.8.8.8" "8.8.4.4" ];
    interfaces.eth0 = {
      ipv4.addresses = [{
        address = "77.90.40.121";
        prefixLength = 24;
      }];
      ipv6.addresses = [{
        address = "2a01:4f8:1c1b:16d01::/64";
        prefixLength = 64;
      }];
    };
    defaultGateway = {
      address = "77.90.40.1";
      interface = "eth0";
    };
    defaultGateway6 = {
      address = "2a0f:85c1:b73::1";
      interface = "eth0";
    };
  };

  environment.systemPackages = with pkgs; [ ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  users.users.kdebre = {
    isNormalUser = true;
    shell = pkgs.fish;
    openssh.authorizedKeys.keys = [
      # change this to your ssh key
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMR5MeTKnY2McxkQKmnLnVjAgkBFQC2XvOI+Sxb/UymV 2025"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKflbf4NOuz7n+o8GB5ntkkC+lHdakrqLpgtZP0pnV// razerphone"
    ];
    extraGroups = [ "wheel" ];
    packages = with pkgs; [ ];
  };
  console.keyMap = "de";
  programs.fish.enable = true;

  system.stateVersion = "24.11";

  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.

  # imports =
  #   [ (modulesPath + "/profiles/qemu-guest.nix")
  #   ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "ahci"
    "sd_mod"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

}
